# Generated by Django 5.0.7 on 2024-08-19 12:25

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_alter_investor_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='conditions',
            field=ckeditor.fields.RichTextField(verbose_name='Shartlar'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='conditions_ru',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Shartlar'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='conditions_uz',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Shartlar'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='partnership_opportunities',
            field=ckeditor.fields.RichTextField(verbose_name='Hamkorlik imkoniyatlari'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='partnership_opportunities_ru',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Hamkorlik imkoniyatlari'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='partnership_opportunities_uz',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Hamkorlik imkoniyatlari'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='partnership_programs',
            field=ckeditor.fields.RichTextField(verbose_name='Hamkorlik dasturlari'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='partnership_programs_ru',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Hamkorlik dasturlari'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='partnership_programs_uz',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Hamkorlik dasturlari'),
        ),
    ]
