# Generated by Django 5.0.7 on 2024-08-19 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_alter_partner_conditions_alter_partner_conditions_ru_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='conditions',
            field=models.TextField(verbose_name='Shartlar'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='conditions_ru',
            field=models.TextField(null=True, verbose_name='Shartlar'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='conditions_uz',
            field=models.TextField(null=True, verbose_name='Shartlar'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='partner/photos/', verbose_name='Rasm'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='partnership_opportunities',
            field=models.TextField(verbose_name='Hamkorlik imkoniyatlari'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='partnership_opportunities_ru',
            field=models.TextField(null=True, verbose_name='Hamkorlik imkoniyatlari'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='partnership_opportunities_uz',
            field=models.TextField(null=True, verbose_name='Hamkorlik imkoniyatlari'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='partnership_programs',
            field=models.TextField(verbose_name='Hamkorlik dasturlari'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='partnership_programs_ru',
            field=models.TextField(null=True, verbose_name='Hamkorlik dasturlari'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='partnership_programs_uz',
            field=models.TextField(null=True, verbose_name='Hamkorlik dasturlari'),
        ),
    ]
