# Generated by Django 5.0.7 on 2024-08-19 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0010_alter_partner_conditions_alter_partner_conditions_ru_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinformation',
            name='company_address',
            field=models.TextField(verbose_name='Kompaniya manzillari'),
        ),
        migrations.AlterField(
            model_name='contactinformation',
            name='company_address_ru',
            field=models.TextField(null=True, verbose_name='Kompaniya manzillari'),
        ),
        migrations.AlterField(
            model_name='contactinformation',
            name='company_address_uz',
            field=models.TextField(null=True, verbose_name='Kompaniya manzillari'),
        ),
    ]
